const axios = require("axios");
const PDFDocument = require("pdfkit");

async function fetchImageBuffer(url) {
  const response = await axios.get(url, {
    responseType: "arraybuffer",
    timeout: 30000,
  });
  return Buffer.from(response.data);
}

async function generateScanReport(res, scan) {
  const patient = scan.userId;
  const confidencePercent = Math.round(scan.confidence * 100);
  const createdAt = new Date(scan.createdAt).toLocaleString();
  const doc = new PDFDocument({ margin: 48, size: "A4" });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=pneumonia-report-${scan._id}.pdf`
  );

  doc.pipe(res);

  doc.fontSize(20).text("Pneumonia Detection Report", { align: "center" });
  doc.moveDown();

  doc.fontSize(12).text(`Patient: ${patient.name}`);
  doc.text(`Email: ${patient.email}`);
  doc.text(`Scan Date: ${createdAt}`);
  doc.text(`Prediction: ${scan.prediction}`);
  doc.text(`Confidence: ${confidencePercent}%`);
  doc.moveDown();

  doc
    .fontSize(10)
    .fillColor("#555555")
    .text(
      "This report is generated by an educational AI assistant and must be reviewed by a qualified clinician."
    );
  doc.fillColor("#000000");
  doc.moveDown();

  try {
    const originalBuffer = await fetchImageBuffer(scan.imageUrl);
    doc.fontSize(13).text("Original X-ray");
    doc.image(originalBuffer, { fit: [230, 180] });
  } catch (error) {
    doc.text("Original X-ray could not be embedded in the PDF.");
  }

  doc.moveDown();

  try {
    const heatmapBuffer = await fetchImageBuffer(scan.heatmapUrl);
    doc.fontSize(13).text("Grad-CAM Heatmap");
    doc.image(heatmapBuffer, { fit: [230, 180] });
  } catch (error) {
    doc.text("Grad-CAM heatmap could not be embedded in the PDF.");
  }

  doc.moveDown();
  doc.fontSize(13).text("Doctor's Note");
  doc.fontSize(11).text(scan.doctorNote || "No doctor's note has been added.");

  doc.end();
}

module.exports = { generateScanReport };

